macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "21.3.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-21.3.0/Contents/Home
    DTLV_PLATFORM: macos
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[d6ff8cdc392157f211c754fa0763875434d1bfde0c00a05e48ba9470003a76c14c9213adb80623f81e13f2f0fa8fbd57]
  script: |
    git submodule init
    git submodule update

    sudo script/install-leiningen
    script/install-graalvm

    export PATH=$GRAALVM_HOME/bin:$PATH
    export JAVA_HOME=$GRAALVM_HOME
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version

    cd native
    script/compile
    dtlv-test0
    dtlv-test1
    dtlv-test2
    rm dtlv-test0
    rm dtlv-test1
    rm dtlv-test2

    7z a -tzip dtlv-${{ github.event.release.tag_name }}-${{ matrix.os }}-amd64.zip dtlv
  binaries_artifacts:
    path: "dtlv-*.zip"
