macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  # only_if: $CIRRUS_TAG != ''
  only_if: "changesInclude('.cirrus.yml', 'src/*', 'native/script/*')"
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.0"
    DTLV_PLATFORM: macos
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[!41f1e85b6e586455cca18744e840eb478625b1e76bdf38741704b504929b3115f541f73101393835ca625e2e9db295a2!]
  script: |

    brew install leiningen
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}/Contents/Home

    script/compile

    ./dtlv-test0

    brew install p7zip

    7z a -tzip dtlv-${CIRRUS_TAG}-macos-latest-aarch64.zip dtlv

    script/upload
