name: Build Datalevin Binaries

on:
  release:
    types:
      - published

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install Native Image
        run: |
          gu install native-image

      - name: Install LMDB
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: sudo apt install liblmdb-dev

      - name: Build datalevin
        run: |
          gu install native-image
          cd native
          bash script/compile

      - name: Run native tests
        run: |
          native/dtlv-test

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          asset_name: datalevin-${{ github.event.release.tag_name }}-linux-amd64.zip
          asset_path: native/dtlv
          asset_content_type: application/zip
          upload_url: ${{ github.event.release.upload_url }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install Native Image
        run: |
          gu install native-image

      - name: Install LMDB
        uses: knicknic/os-specific-run@v1.0.3
        with:
          macos: brew install lmdb leiningen

      - name: Build datalevin
        run: |
          gu install native-image
          cd native
          bash script/compile

      - name: Run native tests
        run: |
          native/dtlv-test

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          asset_name: datalevin-${{ github.event.release.tag_name }}-macos-amd64.zip
          asset_path: native/dtlv
          asset_content_type: application/zip
          upload_url: ${{ github.event.release.upload_url }}
