name: Build Datalevin Binary

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install Native Image
        run: |
          gu install native-image

      - name: Install LMDB
        uses: knicknic/os-specific-run@v1.0.3
        with:
          macos: brew install lmdb leiningen
          linux: sudo apt install liblmdb-dev

      - name: Build native Datalevin
        run: |
          gu install native-image
          cd native
          bash script/compile

      - name: Run native tests
        run: |
          native/dtlv-test

      - name: Zip binary
        id: zip_asset
        run: |
          7z a -tzip dtlv-${{ github.event.release.tag_name }}-${{ matrix.os }}-amd64.zip native/dtlv

      - name: Upload reflect-config.json
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: native/config/reflect-config.json

      - name: Upload binary
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dtlv-${{ github.event.release.tag_name }}-${{ matrix.os }}-amd64.zip
