name: Test workflow

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        gu-binary: [gu, gu.cmd]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: macos-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with: 
          submodules: recursive

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install Native Image
        run: |
          ${{ matrix.gu-binary }} install native-image

      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Test Leiningen
        run: lein -v

      - name: Build Native Datalevin
        run: |
          cd native
          bash script/compile

      - name: Run Native Tests
        run: |
          native/dtlv-test

